// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetOrderViewReq struct {
	OrderID string `form:"order_id"`
}

type OrderViewResp struct {
	OrderID       string `json:"order_id"`
	Status        string `json:"status"`
	AmountCents   int64  `json:"amount_cents"`
	ProviderTxnID string `json:"provider_txn_id,omitempty"`
	SeatNo        string `json:"seat_no,omitempty"`
	UpdatedAt     string `json:"updated_at"`
}
