// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"ticketing-gozero/apps/order-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/cancel",
				Handler: CancelOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/get",
				Handler: GetOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/reserve",
				Handler: ReserveOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/payments/callback",
				Handler: PaymentCallbackHandler(serverCtx),
			},
		},
	)
}
