// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AvailabilityReq struct {
	PartitionKey string `form:"partition_key"`
}

type AvailabilityResp struct {
	PartitionKey string `json:"partition_key"`
	Available    int    `json:"available"`
}

type ConfirmHoldReq struct {
	PartitionKey string `json:"partition_key"`
	HoldID       string `json:"hold_id"`
}

type PartitionStateResp struct {
	PartitionKey string `json:"partition_key"`
	Capacity     int    `json:"capacity"`
	Available    int    `json:"available"`
	Confirmed    int    `json:"confirmed"`
	LastSeq      int64  `json:"last_seq"`
}

type ReleaseHoldReq struct {
	PartitionKey string `json:"partition_key"`
	HoldID       string `json:"hold_id"`
}

type TryHoldReq struct {
	PartitionKey string `json:"partition_key"`
	HoldID       string `json:"hold_id"`
	Qty          int    `json:"qty"`
	Capacity     int    `json:"capacity"`
}

