// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: seatallocator/v1/seatallocator.proto

package seatallocatorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeatAllocator_AllocateSeat_FullMethodName = "/seatallocator.v1.SeatAllocator/AllocateSeat"
)

// SeatAllocatorClient is the client API for SeatAllocator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeatAllocatorClient interface {
	AllocateSeat(ctx context.Context, in *AllocateSeatRequest, opts ...grpc.CallOption) (*AllocateSeatResponse, error)
}

type seatAllocatorClient struct {
	cc grpc.ClientConnInterface
}

func NewSeatAllocatorClient(cc grpc.ClientConnInterface) SeatAllocatorClient {
	return &seatAllocatorClient{cc}
}

func (c *seatAllocatorClient) AllocateSeat(ctx context.Context, in *AllocateSeatRequest, opts ...grpc.CallOption) (*AllocateSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateSeatResponse)
	err := c.cc.Invoke(ctx, SeatAllocator_AllocateSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeatAllocatorServer is the server API for SeatAllocator service.
// All implementations must embed UnimplementedSeatAllocatorServer
// for forward compatibility.
type SeatAllocatorServer interface {
	AllocateSeat(context.Context, *AllocateSeatRequest) (*AllocateSeatResponse, error)
	mustEmbedUnimplementedSeatAllocatorServer()
}

// UnimplementedSeatAllocatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeatAllocatorServer struct{}

func (UnimplementedSeatAllocatorServer) AllocateSeat(context.Context, *AllocateSeatRequest) (*AllocateSeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateSeat not implemented")
}
func (UnimplementedSeatAllocatorServer) mustEmbedUnimplementedSeatAllocatorServer() {}
func (UnimplementedSeatAllocatorServer) testEmbeddedByValue()                       {}

// UnsafeSeatAllocatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeatAllocatorServer will
// result in compilation errors.
type UnsafeSeatAllocatorServer interface {
	mustEmbedUnimplementedSeatAllocatorServer()
}

func RegisterSeatAllocatorServer(s grpc.ServiceRegistrar, srv SeatAllocatorServer) {
	// If the following call pancis, it indicates UnimplementedSeatAllocatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeatAllocator_ServiceDesc, srv)
}

func _SeatAllocator_AllocateSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatAllocatorServer).AllocateSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatAllocator_AllocateSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatAllocatorServer).AllocateSeat(ctx, req.(*AllocateSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeatAllocator_ServiceDesc is the grpc.ServiceDesc for SeatAllocator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeatAllocator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seatallocator.v1.SeatAllocator",
	HandlerType: (*SeatAllocatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateSeat",
			Handler:    _SeatAllocator_AllocateSeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seatallocator/v1/seatallocator.proto",
}
