// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CancelOrderReq struct {
	OrderID      string `json:"order_id"`
	PartitionKey string `json:"partition_key,optional"`
	HoldID       string `json:"hold_id,optional"`
}

type CreateOrderReq struct {
	IdempotencyKey string `json:"idempotency_key"`
	AmountCents    int64  `json:"amount_cents"`
}

type GetOrderReq struct {
	OrderID string `form:"order_id"`
}

type OrderResp struct {
	OrderID        string `json:"OrderID"`
	IdempotencyKey string `json:"IdempotencyKey"`
	Status         string `json:"Status"`
	AmountCents    int64  `json:"AmountCents"`
	CreatedAt      string `json:"CreatedAt"`
	UpdatedAt      string `json:"UpdatedAt"`
}

type PaymentCallbackReq struct {
	OrderID       string `json:"order_id"`
	ProviderTxnID string `json:"provider_txn_id"`
	Status        string `json:"status"`
	PartitionKey  string `json:"partition_key,optional"`
	HoldID        string `json:"hold_id,optional"`
	Signature     string `json:"signature,optional"`
}

type ReserveOrderReq struct {
	OrderID      string `json:"order_id"`
	PartitionKey string `json:"partition_key,optional"`
	HoldID       string `json:"hold_id,optional"`
	Qty          int    `json:"qty,optional"`
	Capacity     int    `json:"capacity,optional"`
}
