// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"ticketing-gozero/apps/inventory-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/inventory/availability",
				Handler: AvailabilityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/confirm-hold",
				Handler: ConfirmHoldHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/release-hold",
				Handler: ReleaseHoldHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/try-hold",
				Handler: TryHoldHandler(serverCtx),
			},
		},
	)
}
